name: jambot
region: nyc  # Choose your preferred region: nyc, sfo, ams, sgp, fra

# Worker service (no HTTP endpoint needed for Discord bot)
workers:
  - name: jambot
    image:
      registry_type: DOCR
      repository: jambot  # Your image name in the registry
      tag: latest

    # Resource limits (adjust as needed)
    instance_count: 1
    instance_size_slug: basic-xxs  # 512MB RAM, 0.5 vCPU (~$5/month)

    # Environment variables (sensitive values set via DigitalOcean console or doctl)
    envs:
      - key: LOG_LEVEL
        value: INFO
      - key: DATABASE_PATH
        value: /data/jambot.db
      - key: LOG_FILE
        value: /data/jambot.log

    # Health check is not applicable for worker services
    # Workers don't have HTTP endpoints

# Note: Volumes are not directly supported in app.yaml
# They must be created and attached via the DigitalOcean console or API
# See DEPLOYMENT.md for volume setup instructions
